# Generated by Django 5.0.7 on 2024-08-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeilaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('contratacao_ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimesEmblemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('emblema', models.ImageField(upload_to='thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('vitoria', models.IntegerField(default=0)),
                ('empate', models.IntegerField(default=0)),
                ('derrota', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinheiro_time', models.DecimalField(decimal_places=2, default=200000, max_digits=100)),
                ('salario_time', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=200000, max_digits=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.IntegerField(blank=True, null=True)),
                ('placar_visitante', models.IntegerField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to=settings.AUTH_USER_MODEL)),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_visitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosEafc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=200, null=True)),
                ('overall', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.ImageField(upload_to='thumbnail')),
                ('nacionalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('posicao', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=4000, max_digits=100)),
                ('salario', models.DecimalField(decimal_places=2, default=2000, max_digits=100)),
                ('comprado', models.BooleanField(default=False)),
                ('time_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed_by_proposer', models.BooleanField(default=False)),
                ('confirmed_by_receiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_made', to=settings.AUTH_USER_MODEL)),
                ('proposer_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer_player', to='core.dadoseafc')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL)),
                ('receiver_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_player', to='core.dadoseafc')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True)),
                ('pagamento', models.BooleanField(default=False)),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('emblema_time', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verificado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
