# Generated by Django 5.0.7 on 2024-08-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoseafc',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='dadoseafc',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='dadoseafc',
            name='time',
        ),
    ]
