# Generated by Django 5.0.7 on 2024-08-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dadoseafc_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoseafc',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
