# Generated by Django 5.0.7 on 2024-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dadoseafc_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentotime',
            name='dinheiro_time',
            field=models.DecimalField(decimal_places=2, default=60000, max_digits=100),
        ),
        migrations.AlterField(
            model_name='orcamentotime',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=60000, max_digits=100),
        ),
    ]
