# Generated by Django 5.0.7 on 2024-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orcamentotime_dinheiro_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacao',
            name='notificacao_true',
            field=models.BooleanField(default=False),
        ),
    ]
