# Generated by Django 5.0.7 on 2024-08-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_verificacao_notificacao_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentotime',
            name='dinheiro_time',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=100),
        ),
        migrations.AlterField(
            model_name='orcamentotime',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=100),
        ),
    ]
