# Generated by Django 5.0.7 on 2024-08-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoseafc',
            name='time_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogador', to='core.team'),
        ),
    ]
