# Generated by Django 5.0.7 on 2024-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_classificacao_jogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='jogos',
            field=models.IntegerField(default=0),
        ),
    ]
