# Generated by Django 5.0.7 on 2024-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_classificacao_jogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
