# Generated by Django 5.0.7 on 2024-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_classificacao_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoseafc',
            name='comprado',
        ),
        migrations.AddField(
            model_name='dadoseafc',
            name='assistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadoseafc',
            name='gols',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadoseafc',
            name='qtd_melhor_campo',
            field=models.IntegerField(default=0),
        ),
    ]
